Release 1.6.3
PF2-pasteur-fr/SARTools-Galaxy pull request #8
Opened 2018-09-25 09:35 UTC by loraine-gueguen

Updated conda dependencies, galaxy wrappers and rscripts to use release 1.6.3 of sartools.

2018-09-28 12:17 UTC, lecorguille requested changes

2018-09-28 12:17 UTC, lecorguille commented on sartools/abims_sartools_deseq2.xml
> +                <param name="fitType" type="select" label="Mean-variance relationship" argument="--fitType" help="Type of model for the mean-dispersion relationship. Parametric by default." >
`argument` fait le boulot de `name` et un peu plus.
Donc tu peux virer `name`

2018-09-28 13:32 UTC, loraine-gueguen commented on sartools/abims_sartools_deseq2.xml
> +                <param name="fitType" type="select" label="Mean-variance relationship" argument="--fitType" help="Type of model for the mean-dispersion relationship. Parametric by default." >
fait

2018-10-01 08:23 UTC, lecorguille approved these changes

2018-10-01 08:24 UTC, merged